blog/urls.py
from django.conf.urls import url, include
try:
  from ratelimitbackend  import admin
except ImportError as e:
  print(e)
  print("WARNING: ratelimitbackend import failed, rate limint for admin site not supported!")
  from django.contrib import admin


urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns =[
  url(r'^$', views.HomeView.as_view(), name='home'),
  url(r'^(?P<page_no>[0-9]+)/$', views.HomeView.as_view(), name='home'),
  url(r'^posts/$', views.PostsView.as_view(), name='posts'),
  url(r'^posts/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
#  url(r'^posts/categories/$', views.CategoryView.as_view(), name='category'),
  url(r'^posts/categories/(?P<category_id_0>[0-9]+)/$', views.CategorisedPostsView.as_view(), name='categorised_posts'),
  url(r'^test/(?P<pk>[0-9]+)/$', views.Test.as_view(), name='test'),
  url(r'^posts/(?P<pk>[0-9]+)/addcomment/$', views.CommentView.as_view(), name='addcomment'),
  url(r'^about/$', views.AboutView.as_view(), name='about'),
  url(r'^test2/$', views.Test2.as_view(), name='Test2'),

]

home/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
class Category(models.Model):
  name = models.CharField(max_length=255, null=True)
  description = models.TextField(blank=True, null=True)
  create_on = models.DateTimeField(auto_now_add=True)
  last_modified = models.DateTimeField(auto_now=True)

  class Meta:
    verbose_name_plural = "Categories"

  def __unicode__(self):
    return self.name

  def __str__(self):
    return self.name

from django.template.defaultfilters import slugify
import re

class Post(models.Model):
  title = models.CharField(max_length=200, null=True)
  slug = models.SlugField(max_length=255, blank=True, null=True)
  category = models.ForeignKey(Category, related_name='post_category', 
    blank=True, null=True, on_delete=models.CASCADE)
#  content = models.TextField(blank=True, null=True)
  content = tinymce_models.HTMLField(blank=True, null=True)
  created_on = models.DateTimeField(auto_now_add=True)
  last_modified = models.DateTimeField(auto_now=True)
  author = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
  approve_comment = models.BooleanField(default=False)
  def approv(self):
    self.approve_comment = True
    self.save()
#  content_head = models.TextField(blank=True, null=True)
  class Meta:
    verbose_name_plural = "Posts"

  def __unicode__(self):
    return self.title

  def save(self, *args, **kwargs):
    self.slug = slugify(self.title)
    super(Post, self).save(*args, **kwargs)

  def get_content_head(self):
    ''' remove the html tags and get text head '''
    f = re.compile(r'</?\w+[^>]*>', re.S)
    html = self.content
    head = f.sub('', html)[:300]
    return head
from django.core.exceptions import ValidationError
def comment_text_validate(value):
  unallowed_strings = ['http://', 'https://',]
  comment_max_length = 500

  for v in unallowed_strings:
    if v in value:
      raise ValidationError(
        "bad comment."
        )

class Comment(models.Model):
  ''' define post comments '''
  post = models.ForeignKey(Post, related_name='comments', 
    on_delete=models.CASCADE)
  author = models.CharField(max_length=200)
  text = models.TextField(max_length=500,validators=[comment_text_validate])
  created_on = models.DateTimeField(auto_now=True)
  approve_comment = models.BooleanField(default=False)
  comment_ip = models.GenericIPAddressField(null=True) # 20170907 21:30
  list_display = ('text', 'post', 'created_on', 'comment_ip', 'author')

  def save(self, *args, **kwargs):
    if self.post.approve_comment:
      super(Comment, self).save(*args, **kwargs)

  def approv(self):
    self.approve_comment = True
    self.save()

  def __unicode__(self):
    return self.text
  def __str__(self):
    return self.text[:20]
  class Meta:
    ''' Make ordering with created_on, when get objects from object.all() '''
    ordering = ['-created_on']


class About(models.Model):
  ''' Define about page content. '''
  title = models.CharField(max_length=200, null=True)
  content = tinymce_models.HTMLField(blank=True, null=True)
  created_on = models.DateTimeField(auto_now_add=True)
  last_modified = models.DateTimeField(auto_now=True)
# about slug: 
# https://github.com/neithere/django-autoslug

# Create your models here.

home/forms.py
from django import forms
from .models import Post, Comment, comment_text_validate
from django.utils.translation import ugettext_lazy as _

class CommentForm(forms.ModelForm):
  name = "comments"
#  text = forms.TextInput(validators=[comment_text_validate])
  class Meta:
    model = Comment
    fields = ['text', 'author']
    labels = {
#      'text': _('Comments'),
    }
    help_texts = {
#      'text': _('Can this work?'),
    }
  
#  def as_p(self):
#   pass 

home/views.py
from django.shortcuts import render
from django.views import generic

from django.http import HttpResponse
from django.template import loader

from .models import Post

# home page view.
class HomeView(generic.TemplateView):
  ''' home page view '''
  template_name = 'home/home.html'
  def get_context_data(self, page_no=1, **kwargs):
    context = super(HomeView, self).get_context_data(**kwargs)
    page_no = int(page_no)
    posts_per_page = 10
    a, b = (page_no-1) * posts_per_page, page_no * posts_per_page
    context['posts'] = Post.objects.order_by('-created_on')[a:b]
    page_no_max = Post.objects.count() / posts_per_page + 1
    context['page_no'] = page_no
    pre = page_no - 1
    nex = page_no + 1
    if (pre < 1):
        context['prev'] = None
    else:
        context['prev'] = pre
    if (nex > page_no_max):
        context['next'] = None
    else:
        context['next'] = nex
    return context

class PostsView(generic.ListView):
  template_name = 'home/posts.html'
  context_object_name = 'posts'
  def get_queryset(self):
    """ Return all of the posts """
    return Post.objects.order_by('-last_modified')

# Categories 
# https://docs.djangoproject.com/en/1.11/topics/class-based-views/mixins/
class Categories(generic.ListView):
  pass

# posts with specified categories.
class CategorisedPostsView(generic.ListView):
  template_name = 'home/category.html'
  context_object_name = 'posts_in_category'
  def get_queryset(self):
    """ Return posts of specified category """
    return Post.objects.filter(category_id=int(self.kwargs['category_id_0']))

# display posts content.
class DetailView(generic.DetailView):
  ''' display posts content '''
  model = Post
  template_name = 'home/detail.html'
  def get_context_data(self, **kwargs):
    context = super(DetailView, self).get_context_data(**kwargs)
    # Get the next page and previous pave.
    try:
      context['next'] = self.get_object().get_next_by_created_on()
    except:
      context['next'] = None
    try:
      context['prev'] = self.get_object().get_previous_by_created_on()
    except:
      context['prev'] = None
    # comment form
#    kwargs['form'] = CommentForm()
    context['form'] = CommentForm
    return context



from django.views.generic.edit import FormView
from .forms import CommentForm
from django.urls import reverse_lazy, reverse
from .models import Comment
from django.shortcuts import get_object_or_404
class CommentView(FormView):
  ''' Page for add comments '''
  form_class = CommentForm
  template_name = 'home/detail.html'
  def get_post_pk(self):
    post_pk = self.kwargs['pk']
    return post_pk

#  success_url = reverse_lazy('home:detail', kwargs={'id':get_post_id()})
# http://blog.csdn.net/zh_m8/article/details/7975639
# https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

  def form_valid(self, form):
    self.success_url = reverse('home:detail', kwargs={'pk':self.get_post_pk()})
    form.instance.comment_ip = self.request.META['REMOTE_ADDR'] 
    a = form.save(commit=False)
#    a.comment_ip = self.get_comment_request().META['REMOTE_ADDR'] # 20170907 21:00
    a.post = Post.objects.get(pk=self.get_post_pk())
    comment_rate_limit = 30
    if self.comment_interval() > comment_rate_limit:
      a.save()    
    return super(CommentView, self).form_valid(form)
  def comment_interval(self):
    ''' Return last comment interval '''
    from django.utils.timezone import utc
    from datetime import datetime
    now = datetime.utcnow().replace(tzinfo=utc)
    request_ip = self.request.META['REMOTE_ADDR']
    try:
      last_comment_created_on = Comment.objects.filter(comment_ip=request_ip).latest('created_on').created_on
      interval = (now-last_comment_created_on).seconds
      return interval
    except Comment.DoesNotExist:
      return 9999999

from .models import About
class AboutView(generic.TemplateView):
  ''' About page view. '''

  template_name = "home/about.html"
  def get_context_data(self, **kwargs):
    context = super(AboutView, self).get_context_data(**kwargs)
    try:
      context['title'] = About.objects.latest('created_on').title
      context['content'] = About.objects.latest('created_on').content
    except About.DoesNotExist:
      pass
    return context


# Test view for purpose of debugging and learn.
class Test(generic.DetailView):
  ''' debugging and learn the machanism of view. '''
  model = Post
  template_name = 'home/test.html'
  def get_context_data(self, **kwargs):
    context = super(Test, self).get_context_data(**kwargs)
    context['content_head'] = self.get_object().get_content_head()
    try:
      context['next'] = self.get_object().get_next_by_created_on()
    except:
      context['next'] = None
    try:
      context['prev'] = self.get_object().get_previous_by_created_on()
    except:
      context['prev'] = None
    return context

from django.views import View
class Test2(View):
  def get(self, request):
    return HttpResponse(request.META['REMOTE_ADDR'])
#def home(request):
#    template = loader.get_template('home/home.html')
#    return HttpResponse(template.render(request))


# Create your views here.

home/templates/home/about.html
{% include "home/header.html" %}
{% include "home/navigation.html" %}

{# About page #}
{% if title %}
{% load static %}
{% autoescape off %}
<h3>{{ title }}</h3>
<p>{{ content }}</p>
{% endautoescape %}
{% else %}
<p>No such page yet.. </p>
{% endif %}
{% include "home/footer.html" %}

home/templates/home/addcomment.html
{% load static %}
<body onload="(generateCaptcha())">
<form action="{% url 'home:addcomment' post.pk %}" method="post" onsubmit="return check()" >
{% csrf_token %}
{# {{ form.as_p }} #}
<!-- <p>Text: <input type="text" name="text" /></p> -->
<textarea name="text" cols="50" rows="4" id="comment_content" required></textarea>
{% if user.is_authenticated %}
<p>Author:<input type="text" name="author" value="{{ user.username }}" required /></p>
{% else %}
<p>Author:<input type="text" name="author" required /></p>
{% endif %}

<input type="text" id="captcha" disabled /><br />
<input type="text" id="inputText" required /><br />
<button onclick="generateCaptcha()">Refresh</button>


<input type="submit" value="Submmit"  />

</form>

<script language="javascript">
var captcha;
 
function generateCaptcha() {
    var a = Math.floor((Math.random() * 10));
    var b = Math.floor((Math.random() * 10));
    var c = Math.floor((Math.random() * 10));
    var d = Math.floor((Math.random() * 10));
    captcha=a.toString()+b.toString()+c.toString()+d.toString();
    document.getElementById("captcha").value = captcha;
}
var denykw=["http://", "https://"] 
function check(){
	var input=document.getElementById("inputText").value;
	var text=document.getElementById("comment_content").value;
	for (var i=0; i<denykw.length; i++) {
		if (text.search(denykw[i]) != -1){
			alert("Key word not allowed: "+denykw[i]);
			return false;
		}
	}
	if (input==captcha) {
		return true;
	}
	else{
                alert('Re-enter the captcha!');
		return false;
	}
}
</script>
</body>

home/templates/home/base.html
{% comment "base.html" %}
base.html
This is the base template of the whole site.
{% endcomment %}

{# navigation #}
<p>
<a href="{% url 'home:home' %}">Home</a>
<a href="{% url 'home:posts' %}">Posts</a>
<a href="/admin/">Admin</a>
</p>
<!-- navigation end -->

home/templates/home/category.html
{# navigation #}
{% include "home/header.html" %}
{% include "home/navigation.html" %}
<!-- navigation end -->

{# posts list #}
{% if posts_in_category %}
{% load static %}
  <ul>
  {% for post in posts_in_category %}
    <li><a href="{% url 'home:detail' post.id %}">{{ post.title }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No posts.</p>
{% endif %}

{% include "home/footer.html" %}
<!-- posts list end -->

home/templates/home/detail.html
{# navigation #}
{% include "home/header.html" %}
{% include "home/navigation.html" %}
<!-- navigation end -->

{# previous and next #}
<p>
{% if prev %}
<a href="{% url 'home:detail' prev.id %}">Previous</a>
{% else %}
<a>No more previous</a>
{% endif %}
{% if next %}
<a href="{% url 'home:detail' next.id %}">Next</a>
{% else %}
<a>No more next</a>
{% endif %}
</p>
<!-- Previous and next end -->

{# Main content #}
{% autoescape off %} 
<h2>{{ post.title }}</h2>
<p>{{ post.created_on }} by {{ post.author }}</p>
<hr />
<p>{{ post.content }}</p>
<hr />
{% endautoescape %}
{# Main content ending #}

{# previous and next #}
{% if prev %}
<a href="{% url 'home:detail' prev.id %}">Previous</a>
{% else %}
<a>No more previous</a>
{% endif %}
{% if next %}
<a href="{% url 'home:detail' next.id %}">Next</a>
{% else %}
<a>No more next</a>
{% endif %}

{# comments #}
{% if post.approve_comment %}
<p>Comments:</p>
{% include "home/addcomment.html" %}

{# <p><a href="{% url 'home:addcomment' post.id %}">Add comment</a></p> #}

{# display comments #}
{% for comment in post.comments.all %}
<p>{{ comment.created_on }} by {{ comment.author }}</p>
<p>{{ comment.text }}<br /></p>
{% empty %}
<p>No comments yet :(</p>
{% endfor %}
{% else %}
<p>Comment is not approved to this article.</p>
{% endif %}

home/templates/home/footer.html
<p>Powered by 
<a href="https://github.com/lufy90/Blog">Blog</a></p>

home/templates/home/home.html
{% include "home/header.html" %}
{% include "home/navigation.html" %}

{# posts list and discrib #}
{% load static %}
<img src="{% static 'home/img/lufy-org-0.svg' %}"></img>

{# previous and next #}
<p>
{% if prev %}
<a href="{% url 'home:home' prev %}">Previous</a>
{% else %}
<a>None</a>
{% endif %}
{% if next %}
<a href="{% url 'home:home' next %}">Next</a>
{% else %}
<a>None</a>
{% endif %}
</p>


{% if posts %}
{% load static %}
{% for post in posts %}
<h3><a href="{% url 'home:detail' post.id %}">{{ post.title }}</a></h3>
<p>{{ post.last_modified }} by {{ post.author }}, {{ post.comments.count }}
comment(s)
</p>
<p>{{ post.get_content_head }}...
<a href="{% url 'home:detail' post.id %}">Full text</a></p>
{% endfor %}
{% else %}
<p>No posts.</p>
{% endif %}

{# previous and next #}
<p>
{% if prev %}
<a href="{% url 'home:home' prev %}">Previous</a>
{% else %}
<a>None</a>
{% endif %}
{% if next %}
<a href="{% url 'home:home' next %}">Next</a>
{% else %}
<a>None</a>
{% endif %}
</p>

{% include "home/footer.html" %}

home/templates/home/navigation.html
{% comment "base.html" %} 
navigation.html
{% endcomment %}
<p><a href="{% url 'home:home' %}">Home</a>
<a href="{% url 'home:posts' %}">Posts</a> 

<a href="{% url 'home:about' %}">About</a>
<a href="/admin/">Admin</a> 


</p>

home/templates/home/posts.html
{# navigation #}
{% include "home/header.html" %}
{% include "home/navigation.html" %}
<!-- navigation end -->

{# posts list #}
{% if posts %}
{% load static %}
  <table border="1">
  <tr><th>Title</th> <th>Category</th>  <th>Author</th>  <th>Date</th></tr>
  {% for post in posts %}
    <tr>
    <td><a href="{% url 'home:detail' post.id %}">{{ post.title }}</a></td>
    <td>
      {% if post.category %}
        <a href="{% url 'home:categorised_posts' post.category_id %}">{{ post.category }}</a>
      {% else %}
        {{ post.category }}
      {% endif %}
    </td>
    <td>{{ post.author }}</td>
    <td>{{ post.created_on }}</td>
    </tr>
  {% endfor %}
  </table>
{% else %}
  <p>No posts.</p>
{% endif %}
{% include "home/footer.html" %}
<!-- posts list end -->

home/templates/home/test.html
{% include "home/base.html" %}
{% if prev %}
<p>
<a href="{% url 'home:test' prev.id %}">Previous</a>
{% else %}
<a>No more previous</a>
{% endif %}
{% if next %}
<a href="{% url 'home:test' next.id %}">Next</a>
{% else %}
<a>No more next</a>
</p>
{% endif %}

{# Main content #}
{% autoescape off %} 
<h2>{{ post.title }}</h2>
<p>by {{ post.author }}</p>
<p>head {{ content_head }} headend</p>
<p>{{ post.content|truncatewords:"100" }}</p>
{% endautoescape %}
{# Main content ending #}


{% if prev %}
<a href="{% url 'home:test' prev.id %}">Previous</a>
{% else %}
<a>No more previous</a>
{% endif %}
{% if next %}
<a href="{% url 'home:test' next.id %}">Next</a>
{% else %}
<a>No more next</a>
{% endif %}
{% include "home/base.html" %}

{% if user.is_authenticated %}
<p> {{ user.username }}</p>
{% endif %}